# Workflow for link checking with lychee
name: Link Check Source Files with Lychee

on:
  # Runs weekly every Sunday at 05:00 UTC (midnight EST)
  schedule:
    - cron: '0 5 * * 0'
  # Runs on pull requests targeting the dev branch
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # NOTE: Lychee (and sphinx) encounter issues with SSL certificates for INCF URLs, so use --insecure
          args: --verbose --no-progress './content/**/*.md' './content/**/*.html' './content/**/*.rst' --insecure
